; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
; 
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
; 
; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defn fib [n] 
  (if (<= n 1) 
    1
    (+ (fib (- n 1)) (fib (- n 2)))
  )
)

(defn add-fibs 
  [sum x]
  (let [res (fib x)] 
    (if (<= res 4000000)
      (recur (if (even? res) (+ sum res) sum) (inc x))
      sum)
  )
)
    
(print (add-fibs 0 0))